#!/bin/bash

# get name of file to be read

echo -n "filename> "
read filename

# check that file exists or exit

if [ ! -f $filename ]; then
    echo "No such file: $filename"
    exit
else # determine if file is readable
    if [ ! -r $filename ]; then
        echo "$filename is not writable"
        exit
    fi
    # determine if file is writable
    if [ ! -w $filename ]; then
        echo "$filename is not readable"
        exit
    fi
fi
